env:
  node: true
extends:
  - eslint:recommended
  - uphold
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
  - vitest
root: true
