name: Release
run-name: Release - ${{ github.event.inputs.PACKAGE }}

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: 'The package you wish to release'
        type: choice
        options:
        - opentelemetry-baggage-span-processor
        - opentelemetry-mutable-baggage
        required: true
      VERSION_BUMP:
        description: 'The version bump'
        type: choice
        options:
        - major
        - minor
        - patch
        default: minor
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: 1
    environment: release
    env:
      NPM_WORKSPACE: packages/${{ github.event.inputs.PACKAGE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

    - name: Setup Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install node packages
      run: npm ci

    - name: Configure git
      run: |
        git config user.name "Uphold"
        git config user.email "bot@uphold.com"

    - name: Generate release
      env:
        NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        npm run release --workspace $NPM_WORKSPACE -- --increment ${{ github.event.inputs.VERSION_BUMP }} -V
